/**
 * Common constants for all features.
 */
export default class CommonConstants {
  static readonly text_full_wt1: string = '100%';
  static readonly text_full_he1: string = '100%';
  static readonly index1_title: string = '一级页面';
  static readonly index1_message1: string = '一级页面的数据';
  static readonly index2_url1: string = 'pages/BPage';
  static readonly index2_title1: string = '二级页面';
  static readonly index2_src1: string = 'src';
  static readonly font_size1: string = '16fp';
  static readonly font_size2: string = '20fp';
  static readonly font_size3: string = '38fp';
  static readonly layout_size1: string = '40vp';
  static readonly layout_size2: string = '140vp';
  static readonly layout_size3: string = '296vp';
  static readonly text_font1: string = '30fp';
  static readonly text_wt1: string = '20vp';
  /**
   * The param opacity.
   */
  static readonly PARAMS_OPACITY: number = 0.6;
}