export class ResUtils {


  static get_string_1(): Resource {
    return $r('app.string.tip1')
  }
  static get_string_2(): Resource {
    return $r('app.string.tip2')
  }
  static get_string_3(): Resource {
    return $r('app.string.tip3')
  }
  static get_string_4(): Resource {
    return $r('app.string.tip4')
  }
  static get_string_5(): Resource {
    return $r('app.string.tip5')
  }
  static get_string_6(): Resource {
    return $r('app.string.tip6')
  }




  static get_icon1(): Resource {
    return $r('app.media.arrow')
  }



}