export class ResUtils {
  /**
   * color bufen
   * @returns
   */
  static get_colorFE5756(): Resource {
    return $r('app.color.colorFE5756')
  }

  static get_colorF8F8F8(): Resource {
    return $r('app.color.colorF8F8F8')
  }

  static get_colorF1F3F5(): Resource {
    return $r('app.color.colorF1F3F5')
  }

  static get_color0A59F7(): Resource {
    return $r('app.color.color0A59F7')
  }

  static get_colorCCDFFF(): Resource {
    return $r('app.color.colorCCDFFF')
  }

  static get_colorF3F4F7(): Resource {
    return $r('app.color.colorF3F4F7')
  }
  static get_color182431(): Resource {
    return $r('app.color.color182431')
  }
  /**
   * color bufen
   * @returns
   */

  /**
   * float bufen
   * @returns
   */
  static get_size_opacity_06(): Resource {
    return $r('app.float.size_opacity_06')
  }
  static get_size_fp_16(): Resource {
    return $r('app.float.size_fp_16')
  }
  static get_size_fp_20(): Resource {
    return $r('app.float.size_fp_20')
  }
  static get_size_vp_119(): Resource {
    return $r('app.float.size_vp_119')
  }
  static get_size_vp_105(): Resource {
    return $r('app.float.size_vp_105')
  }
  static get_size_vp_35(): Resource {
    return $r('app.float.size_vp_35')
  }
  static get_size_fp_26(): Resource {
    return $r('app.float.size_fp_26')
  }

  /**
   * float bufen
   * @returns
   */





  /**
   * string bufen
   * @returns
   */
  static get_string_1(): Resource {
    return $r('app.string.tip1')
  }

  static get_string_2(): Resource {
    return $r('app.string.tip2')
  }

  static get_string_3(): Resource {
    return $r('app.string.tip3')
  }

  static get_string_4(): Resource {
    return $r('app.string.tip4')
  }

  static get_string_5(): Resource {
    return $r('app.string.tip5')
  }

  static get_string_6(): Resource {
    return $r('app.string.tip6')
  }
  static get_healthy_life_text(): Resource {
    return $r('app.string.healthy_life_text')
  }
  static get_healthy_life_introduce(): Resource {
    return $r('app.string.healthy_life_introduce')
  }
  /**
   * string bufen
   * @returns
   */


  /**
   * icon bufen
   * @returns
   */
  static get_icon1(): Resource {
    return $r('app.media.arrow')
  }
  static get_icon2(): Resource {
    return $r('app.media.ic_launcher_background')
  }
  static get_icon3(): Resource {
    return $r('app.media.ic_logo')
  }
  /**
   * icon bufen
   */







}